const data = {
  products: [
    {
      name: "Free Shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      description: "A free shirt",
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
    },
    {
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      description: "A fit shirt",
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
    },
    {
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      description: "A free shirt",
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
    },
    {
      name: "Golf Pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      description: "Smart Looking Pants",
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
    },
    {
      name: "Fit Pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 95,
      description: "A popular pants",
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
    },
    {
      name: "Classic Pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 75,
      description: "A popular pants",
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
    },
  ],
};

export default data;
