import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      description: "A free shirt",
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      description: "A fit shirt",
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      description: "A free shirt",
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      description: "Smart Looking Pants",
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 95,
      description: "A popular pants",
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 75,
      description: "A popular pants",
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
    },
  ],
};

export default data;
